name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AMPLIFY_GITHUB_TOKEN: ${{ secrets.AMPLIFY_GITHUB_TOKEN }}
        AWS_DEFAULT_REGION: "eu-west-3"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.2

      - name: Install dependencies
        run: npm install

      - name: Terraform Init
        working-directory: ./TerraformFront
        run: terraform init

      # - name: Terraform Plan
      #   working-directory: ./TerraformFront
      #   run: terraform plan

      - name: Terraform Apply
        working-directory: ./TerraformFront
        env:
          TF_VAR_amplify_github_token: ${{ secrets.AMPLIFY_GITHUB_TOKEN }}
        run: terraform apply -auto-approve
