name: CI Pipeline

on:
  push:
    branches:
      - main
      - devGT
      - devpa

jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

  jest:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    container:
      image: sonar-source/sonarcloud-scan:3.1.0
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.organization=optimalorchestrators_frontend \
            -Dsonar.projectKey=optimalorchestrators \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
