name: CI pipeline

stages:
  - cypress
  - jest
  - eslint
  - sonarcloud
  
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
     - dev
  
jobs:
  cypress:
    image: cypress/browsers:22.12.0
    stage: test
    script:
      - npm install
      - npx install cypress &
      - yarn run cypress open
    only: dev

  jest:
    image: node:18-alpine
    stage: jest
    script:
      - npm install
      - npm test


  eslint:
    image: node:18-alpine
    stage: lint
    script:
     - npm install
     - npm run lint


  sonarcloud:
    image: sonarsource/sonarcloud-scan:3.1.0
    stage: sonarcloud
    script: 
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      args: >
        -Dsonar.organization=optimalorchestrators_frontend
        -Dsonar.projectKey=optimalorchestrators
        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
